name: Actualizar datos de Google Scholar

on:
  schedule:
    - cron: "0 3 * * *"   # todos los d√≠as a las 03:00 UTC
  workflow_dispatch:      # permite ejecutarlo manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias R
        run: |
          Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
          Rscript -e 'remotes::install_github("jkeirstead/scholar")'


      - name: Ejecutar script
        run: |
          Rscript update/update.scholar.R

      - name: Commit y push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-update scholar data" || echo "No changes"
          git push
