name: update-scholar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # cada día

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar paquetes
        run: |
          pip install scholarly

      - name: Ejecutar script
        run: python update/update.scholar.py

      - name: Commit y push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add scholar.csv
          git commit -m "Actualización automática Scholar (Python)" || echo "Sin cambios"
          git push

